import pdfkit
import os

def generate_html_report(scan_results, url):
    html_content = f"""
    <html>
    <head>
        <title>Detailed Security Report</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 20px;
            }}
            h1 {{
                color: #2c3e50;
            }}
            h2 {{
                color: #2980b9;
            }}
            code {{
                background: #f4f4f4;
                padding: 2px 4px;
                border-radius: 4px;
            }}
            pre {{
                background: #f4f4f4;
                padding: 10px;
                border-left: 4px solid #ccc;
                overflow-x: auto;
            }}
            ul {{
                list-style: none;
                padding-left: 0;
            }}
            li::before {{
                content: '• ';
                color: #333;
                margin-right: 5px;
            }}
        </style>
    </head>
    <body>
        <h1>Web Application Security Scan Report</h1>
        <h3>Target URL: <code>{url}</code></h3>
        <hr>
        <h2>Scan Results:</h2>
        <ul>
    """

    # SQL Injection Section
    if scan_results['SQL Injection']:
        html_content += """
        <li><b>⚠️ SQL Injection: Vulnerable</b>
            <ul>
                <li><b>Description:</b> User input is being directly inserted into a SQL query string.</li>
                <li><b>Risk:</b> Attackers can manipulate the query to retrieve, update, or delete database content.</li>
                <li><b>❌ Vulnerable Code:</b>
                    <pre>
user_input = request.args.get("id")
query = "SELECT * FROM users WHERE id = '" + user_input + "'"
cursor.execute(query)
                    </pre>
                </li>
                <li><b>✅ Secure Fix (Parameterized Query):</b>
                    <pre>
user_input = request.args.get("id")
query = "SELECT * FROM users WHERE id = ?"
cursor.execute(query, (user_input,))
                    </pre>
                </li>
                <li><b>Test Payload Used:</b> <code>?id=' OR '1'='1</code></li>
            </ul>
        </li>
        """
    else:
        html_content += "<li><b>✔ SQL Injection: Safe</b></li>"

    # XSS Section
    if scan_results['XSS']:
        html_content += """
        <li><b>⚠️ Cross-Site Scripting (XSS): Vulnerable</b>
            <ul>
                <li><b>Description:</b> Input is directly rendered into the HTML without sanitization.</li>
                <li><b>❌ Vulnerable Code:</b>
                    <pre>
&lt;div&gt;Hello, &lt;script&gt;alert('XSS')&lt;/script&gt;&lt;/div&gt;
                    </pre>
                </li>
                <li><b>✅ Secure Fix (Escaping Output):</b>
                    <pre>
&lt;div&gt;Hello, {{ user_input | e }}&lt;/div&gt;
                    </pre>
                </li>
                <li><b>Test Payload Used:</b> <code>?input=&lt;script&gt;alert('XSS')&lt;/script&gt;</code></li>
            </ul>
        </li>
        """
    else:
        html_content += "<li><b>✔ Cross-Site Scripting (XSS): Safe</b></li>"

    # Outdated Libraries Section
    outdated = scan_results['Outdated Libraries']
    if outdated:
        html_content += "<li><b>⚠️ Outdated Libraries Detected:</b><ul>"
        for lib in outdated:
            html_content += f"<li>{lib}</li>"
        html_content += "</ul></li>"
    else:
        html_content += "<li><b>✔ Outdated Libraries: None</b></li>"

    html_content += """
        </ul>
        <hr>
        <p>Generated by <i>Web Application Security Scanner</i>.</p>
    </body>
    </html>
    """

    # Save HTML to templates folder
    html_path = os.path.join("templates", "report.html")
    with open(html_path, "w", encoding="utf-8") as file:
        file.write(html_content)
    print(f"✅ HTML report saved to {html_path}")

    # PDF saving location
    pdf_folder = "report_pdf"
    os.makedirs(pdf_folder, exist_ok=True)
    pdf_path = os.path.join(pdf_folder, "report.pdf")

    # Generate PDF
    try:
        config = None
        if os.name == 'nt':
            config = pdfkit.configuration(
                wkhtmltopdf=r"C:\tools\wkhtmltopdf\bin\wkhtmltopdf.exe"
            )

        pdfkit.from_file(html_path, pdf_path, configuration=config)
        print(f"✅ PDF report saved to {pdf_path}")
    except Exception as e:
        print(f"❌ PDF generation failed: {e}")
